name: Deploy documentation

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
      - docs-page

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install pdoc -r requirements.txt

      - name: Build documentation
        run: pdoc evolin -d numpy --math -o ./docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs